add missing #include <new> (#733)
* add missing #include <new>

Fix compilation error with clang 21 and c++23:

error: no member named 'launder' in namespace 'std'
  143 |             return std::launder(reinterpret_cast<const rpp::disposable_wrapper*>(&m_data[i * sizeof(rpp::disposable_wrapper)]));

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Aleksey Loginov <victimsnino@gmail.com>