add missing #include <new>
Fix compilation error with clang 21 and c++23:

error: no member named 'launder' in namespace 'std'
  143 |             return std::launder(reinterpret_cast<const rpp::disposable_wrapper*>(&m_data[i * sizeof(rpp::disposable_wrapper)]));